apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: agilesolutions/ui
      context: ../ui
      jib: {}
    - image: agilesolutions/organization
      context: ../organization
      jib: {}
    - image: agilesolutions/leave
      context: ../leave
      jib: {}
    - image: agilesolutions/meeting
      context: ../meeting
      jib: {}
    - image: agilesolutions/notification
      context: ../notification
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
